version: '3.7'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=keycloak"
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK:-postgres}

  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - "9091:8080"
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_LOG_INFO=INFO"
      - "KC_DB=postgres"
      - "KC_DB_USERNAME=keycloak"
      - "KC_DB_PASSWORD=password"
      - "KC_DB_SCHEMA=keycloak"
      - "KC_DB_URL_HOST=postgres"
    depends_on:
      - postgres
    networks:
      - ${GLOBAL_NETWORK:-postgres}
volumes:
  postgres_data:
    driver: local
