server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/frankyiu/microservices-demo-config-server.git
          username: frankyiu
          password: '{cipher}99c8edb7ec8eb9ea5ac9a5c3a184d56de101033c678e98cb440a1072043f07e152a05f6cae476dfd2742de52773856d385ae622ea435229751090bd805f52ac0'
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}90ca707ec213a65420e08b54f9bd30e6de7a94454adbe3710c6c2dcf7d84605bae646607a26747761b2f22dfe462902a'


logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG