server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/frankyiu/Documents/projects/javaworkspace/microservices-demo/config-server-repository
          uri: https://github.com/frankyiu/microservices-demo-config-server.git
          username: frankyiu
          password: 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
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG